namespace Domain.Model.Errors;

/// <summary>
/// Códigos de erro gerados pelas validações das entidades
/// </summary>
public enum ErroEntidade
{
    UF_SIGLA_INVALIDA,
    UF_NOME_INVALIDO,
    UF_SIGLA_JA_EXISTE,
    UF_NAO_PODE_EXCLUIR,

    ENDERECO_LOGRADOURO_INVALIDO,
    ENDERECO_NUMERO_INVALIDO,
    ENDERECO_COMPLEMENTO_INVALIDO,
    ENDERECO_BAIRRO_INVALIDO,
    ENDERECO_CEP_INVALIDO,
    ENDERECO_UF_INVALIDA,

    CLIENTE_RG_INVALIDO,

    CLIENTE_CPF_INVALIDO,
    CLIENTE_NOME_INVALIDO,
    CLIENTE_EMAIL_INVALIDO,
    CLIENTE_ENDERECO_INVALIDO,
    CLIENTE_TELEFONE_INVALIDO,
    CLIENTE_CPF_JA_EXISTE,
    CLIENTE_EMAIL_JA_EXISTE,
    CLIENTE_NAO_ENCONTRADO,
    CLIENTE_NAO_PODE_EXCLUIR,

    PRODUTO_CODIGO_BARRAS_INVALIDO,
    PRODUTO_DESCRICAO_INVALIDA,
    PRODUTO_PRECO_INVALIDO,
    PRODUTO_CODIGO_BARRAS_JA_EXISTE,
    PRODUTO_NAO_ENCONTRADO,
    PRODUTO_NAO_PODE_EXCLUIR,

    PEDIDO_CLIENTE_INVALIDO,
    PEDIDO_ENDERECO_INVALIDO,
    PEDIDO_NAO_ENCONTRADO,
    PEDIDO_NAO_PODE_EXCLUIR,

    ITEM_PEDIDO_INVALIDO,
    ITEM_PRODUTO_INVALIDO,
    ITEM_QUANTIDADE_INVALIDA,
    ITEM_PRECO_INVALIDO,

    PREFERENCIA_DESCRICAO_INVALIDA,
    PREFERENCIA_DESCRICAO_JA_EXISTE,
    PREFERENCIA_NAO_ENCONTRADA,
    PREFERENCIA_NAO_PODE_EXCLUIR
}
