@Api_HostAddress = http://localhost:5167

GET {{Api_HostAddress}}/api/cliente
Accept: application/json

###

GET {{Api_HostAddress}}/api/cliente/36718168050
Accept: application/json

###

GET {{Api_HostAddress}}/api/cliente/12345678901
Accept: application/json

###

POST {{Api_HostAddress}}/api/cliente
Content-type: application/json

{
    "cpf": "22237067031",
    "nome": "Jose da Silva",
    "email": "jose.silva@gmail.com",
    "password": "123456",
    "logradouro": "Rua Barão de Mesquita",
    "numero": "100",
    "complemento": "ap 101",
    "bairro": "Tijuca",
    "cep": "20540006",
    "uf": "RJ"
}


###

POST {{Api_HostAddress}}/api/uf
Content-type: application/json

{
    "sigla": "ES",
    "nome": "Espírito Santo"
}

###
GET {{Api_HostAddress}}/api/uf/RJ
Accept: application/json

###

GET {{Api_HostAddress}}/api/uf/XX
Accept: application/json

###

GET {{Api_HostAddress}}/api/uf
Accept: application/json

###

DELETE {{Api_HostAddress}}/api/uf/RJ
Accept: application/json

###

POST {{Api_HostAddress}}/api/preferencia
Content-type: application/json

{
    "descricao": "Natação"
}

###

GET {{Api_HostAddress}}/api/preferencia/
Accept: application/json

###

GET {{Api_HostAddress}}/api/preferencia/d8eacde5-b097-48e1-bcc7-1856cf3c0d13
Accept: application/json