@Api_HostAddress = http://localhost:5167

GET {{Api_HostAddress}}/api/cliente
Accept: application/json

###

GET {{Api_HostAddress}}/api/cliente/36718168050
Accept: application/json

###

GET {{Api_HostAddress}}/api/cliente/12345678901
Accept: application/json

###

POST {{Api_HostAddress}}/api/cliente
Content-type: application/json

{
    "cpf": "22237067030",
    "nome": "Jose da Silva",
    "email": "jose.silva@gmail.com",
    "password": "123456",
    "logradouro": "",
    "numero": "100",
    "complemento": "ap 101",
    "bairro": "Tijuca",
    "cep": "2054000",
    "uf": "RJ"
}

###

POST {{Api_HostAddress}}/api/cliente
Content-type: application/json

{
    "cpf": "36718168050",
    "nome": "Maria Isabel",
    "email": "maria.isabel@gmail.com",
    "password": "234567",
    "logradouro": "Rua das Margaridas",
    "numero": "200",
    "complemento": "ap 202",
    "bairro": "Maracanã",
    "ddd": "21",
    "telefone": "987654321",
    "cep": "21000000",
    "uf": "RJ"
}

###

POST {{Api_HostAddress}}/api/uf
Content-type: application/json

{
    "sigla": "ES",
    "nome": "Espírito Santo"
}

###
GET {{Api_HostAddress}}/api/uf/RJ
Accept: application/json

###

GET {{Api_HostAddress}}/api/uf/XX
Accept: application/json

###

GET {{Api_HostAddress}}/api/uf
Accept: application/json

###

DELETE {{Api_HostAddress}}/api/uf/RJ
Accept: application/json

###

POST {{Api_HostAddress}}/api/preferencia
Content-type: application/json

{
    "descricao": "Natação"
}

###

GET {{Api_HostAddress}}/api/preferencia/
Accept: application/json

###

POST {{Api_HostAddress}}/api/produto
Content-type: application/json

{
    "codigoBarras": "5555555555555",
    "descricao": "Produto QUATRO",
    "moeda": "R$",
    "preco": "400"
}

###

GET {{Api_HostAddress}}/api/produto/
Accept: application/json

###

GET {{Api_HostAddress}}/api/produto/3456789012345
Accept: application/json

###

DELETE {{Api_HostAddress}}/api/produto/5555555555555
Accept: application/json
